  _format_version: "3.0"
  services:
    - name: public-auth-service
      url: http://host.docker.internal:8080/public
      routes:
        - name: public-auth-route
          paths:
            - /api/v1/auth/public
          strip_path: true

    - name: secure-auth-service
      url: http://host.docker.internal:8080/secure
      routes:
        - name: secure-auth-route
          paths:
            - /api/v1/auth/secure
          strip_path: true
          plugins:
            - name: jwt

  consumers:
    - username: default-consumer-client
      jwt_secrets:
        - algorithm: RS256
          key: https://skullprogrammer.tech/issuer
          rsa_public_key: my-secret-token
